# Basic
title: OneV's Den
subtitle: 上善若水，人淡如菊
welcome_message: <a href="https://objccn.io/products/">我组织的 ObjC 中国与 objc.io 合作发布了一系列 iOS/Swift 相关图书，欢迎访问了解更多</a>
description: 嗨，我是王巍 (@onevcat)，一名 iOS 开发者。
creator: <a href="https://onev.cat">@onevcat</a>

url: "https://onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: '//onev.cat'}
    - {title: 工具, description: 我所使用的 app 们, url: '/apps'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    mail: onev@onevcat.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: onevcat.com
