# Basic
title: OneV's Den
subtitle: 上善若水，人淡如菊
welcome_message: <a href="http://swifter.tips" target="_blank">Swifter.tips - 我维护的 Swift 使用技巧分享网站，每周三更新，欢迎访问</a>
description: 嗨，我是王巍 (@onevcat)，一名来自中国的 iOS / Unity 开发者。现居日本，就职于 LINE。正在修行，探求创意之源。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 项目, description: 我的项目, url: 'http://project.onevcat.com'}
    - {title: 关于, description: 了解更多关于我, url: 'http://about.onevcat.com/'}
    - {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: onevcat.com
